#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

define("__CA_DB_HOST__", $OPENSHIFT_DB_HOST:$OPENSHIFT_DB_PORT);

# __CA_DB_USER__ = Database login user name
#
define("__CA_DB_USER__", 'my_database_user');

# __CA_DB_PASSWORD__ = Database login password
#
define("__CA_DB_PASSWORD__", 'my_database_password');

# __CA_DB_DATABASE__ = The name of your CollectiveAccess database
#
define("__CA_DB_DATABASE__", 'name_of_my_database');
