#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
    mkdir $OPENSHIFT_DATA_DIR/media
fi
ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/php/media

if [ ! -d $OPENSHIFT_DATA_DIR/import ]; then
    mkdir $OPENSHIFT_DATA_DIR/import
fi
ln -sf $OPENSHIFT_DATA_DIR/import $OPENSHIFT_REPO_DIR/php/import
